const Projects = [
    {
        id: 1,
        image: './../img/danilo-portfolio.png',
        projetoLink: 'https://portfolio-react-seven-beta.vercel.app/',
        codigoLink: 'https://github.com/danilogomes08/portfolio-react',
        category: 'reactJS', 
    },
    {
        id: 2,
        image: './../img/logo-pokemonV2.png',
        projetoLink: 'https://pokedexv2-lake.vercel.app',
        codigoLink: 'https://github.com/danilogomes08/pokedexv2',
        category: 'reactJS', 
    },
    {
        id: 3,
        image: './../img/home-defense.png',
        projetoLink: 'https://marceloesperandio.com.br/taticas',
        codigoLink: '',
        category: 'elementor', 
    },
    {
        id: 4,
        image: './../img/tropa-logo.png',
        projetoLink: 'https://rickchesther.com.br/aguias',
        codigoLink: '',
        category: 'elementor', 
    },
    {
        id: 5,
        image: './../img/rick-logo.png',
        projetoLink: 'https://rickchesther.com.br',
        codigoLink: '',
        category: 'elementor', 
    },
    {
        id: 6,
        image: './../img/espiritualidade-plena.png',
        projetoLink: 'https://americobarbosa.com.br/espiritualidade-plena',
        codigoLink: '',
        category: 'elementor', 
    },
    {
        id: 7,
        image: './../img/chakra-olho.png',
        projetoLink: 'https://americobarbosa.com.br/chakra',
        codigoLink: '',
        category: 'elementor', 
    },
    {
        id: 8,
        image: './../img/cn-logo.png',
        projetoLink: 'https://carvalhonascimento.adv.br',
        codigoLink: '',
        category: 'elementor', 
    },
    {
        id: 9,
        image: './../img/logo-katy.png',
        projetoLink: 'https://katylessons.com.br',
        codigoLink: '',
        category: 'elementor', 
    },
    {
        id: 10,
        image: './../img/plexo-solar.png',
        projetoLink: 'https://americobarbosa.com.br/plexo-solar',
        codigoLink: '',
        category: 'elementor', 
    },
    {
        id: 11,
        image: './../img/chakra-raiz.png',
        projetoLink: 'https://americobarbosa.com.br/chakra-raiz',
        codigoLink: '',
        category: 'elementor', 
    },
    {
        id: 12,
        image: './../img/logo-alpinista.png',
        projetoLink: 'https://americobarbosa.com.br/espiritualidade-pratica',
        codigoLink: '',
        category: 'elementor', 
    },
    {
        id: 13,
        image: './../img/logo-couldbuilder.png',
        projetoLink: 'https://danilogomes08.github.io/cobuild',
        codigoLink: 'https://github.com/danilogomes08/cobuild',
        category: 'hcj', 
    },
    {
        id: 14,
        image: './../img/logo-cozy.png',
        projetoLink: 'https://danilogomes08.github.io/cozy-house/',
        codigoLink: 'https://github.com/danilogomes08/cozy-house',
        category: 'sass', 
    },
    {
        id: 15,
        image: './../img/logo-interact.png',
        projetoLink: 'https://danilogomes08.github.io/Interact',
        codigoLink: 'https://github.com/danilogomes08/Interact',
        category: 'bootstrap', 
    },
    {
        id: 16,
        image: './../img/logo-medidove.png',
        projetoLink: 'https://danilogomes08.github.io/medidove',
        codigoLink: 'https://github.com/danilogomes08/medidove',
        category: 'hcj', 
    },
    {
        id: 17,
        image: './../img/logo-open.png',
        projetoLink: 'https://danilogomes08.github.io/weather',
        codigoLink: 'https://github.com/danilogomes08/weather',
        category: 'reactJS', 
    },
    {
        id: 18,
        image: './../img/econverse.png',
        projetoLink: 'https://teste-front-end-jr-seven.vercel.app',
        codigoLink: 'https://github.com/danilogomes08/teste-front-end-jr',
        category: 'reactJS', 
    },
    {
        id: 19,
        image: './../img/logo-pokemon.png',
        projetoLink: 'https://danilogomes08.github.io/pokedex/',
        codigoLink: 'https://github.com/danilogomes08/pokedex',
        category: 'reactJS', 
    },
    {
        id: 20,
        image: './../img/logo-semana3saudes.png',
        projetoLink: 'https://americobarbosa.com.br/semana-das-saudes-org/',
        codigoLink: '',
        category: 'elementor', 
    },
    {
        id: 21,
        image: './../img/logo-softwerk.png',
        projetoLink: 'https://danilogomes08.github.io/softwerk/',
        codigoLink: 'https://github.com/danilogomes08/softwerk',
        category: 'hcj', 
    },
    {
        id: 22,
        image: './../img/logo-els.png',
        projetoLink: 'https://lp.elsprime.com.br/',
        codigoLink: '',
        category: 'elementor', 
    }
]

export default Projects